### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by celorodovalho** [tgalopin/FOSMessage-demo#1]
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getFirstUnreadMessage" of class "FOS\Message\Driver\Doctrine\ORM\Entity\Conversation"." at /media/Volume8/Desenvolvimento/www/FOSMessage-demo/src/AppBundle/Twig/MessagesExtension.php line 61

**Comment by tgalopin** [comment]
It should work as I added the method (https://github.com/FriendsOfSymfony/FOSMessage/blob/master/src/Model/Conversation.php). I probably forgot to update the composer.lock, can you run `composer update`?

**Comment by celorodovalho** [comment]
Yes!
Thanks!

**Comment by tgalopin** [comment]
I updated the composer.lock, you should be able to use it properly now if you want :) . There was an issue with FOSUserBundle that I solved.
